const state={rooms:new Map(),decisions:[],confirmations:[]};
const $=id=>document.getElementById(id);const fmtTime=iso=>new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(iso));
const demoScenarios=[{room_id:'Q-204',sensor_status:'online',occupied:false,hvac_on:true,light_on:false,power_w:1260,synthetic:true},{room_id:'Q-205',sensor_status:'online',occupied:true,hvac_on:true,light_on:true,power_w:980,synthetic:true},{room_id:'Q-206',sensor_status:'offline',occupied:null,hvac_on:true,light_on:false,power_w:1110,synthetic:true}];
async function evaluate(event){const payload={...event,occurred_at:new Date().toISOString(),synthetic:true};let decision;try{const res=await fetch('/api/evaluate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!res.ok)throw new Error(`HTTP ${res.status}`);decision=await res.json()}catch(error){decision=fallbackEvaluate(payload,error.message)}decision.id=crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`;decision.created_at=new Date().toISOString();decision.resolved=false;state.decisions.unshift(decision);state.rooms.set(payload.room_id,{event:payload,decision});render();return decision}
function fallbackEvaluate(e,note){let classification='OK',rule_id='LOCAL-OK',title='Sem ação operacional',rationale='Evento avaliado no modo local.';if(e.sensor_status!=='online'||e.occupied===null){classification='REVIEW';rule_id='LOCAL-SENSOR';title='Presença indisponível';rationale='Sensor sem contexto confiável.'}else if(e.occupied===false&&(e.hvac_on||e.light_on)){classification='ALERT';rule_id='LOCAL-ENERGY';title='Consumo incompatível com quarto vazio';rationale='Carga ligada em quarto vazio.'}return{room_id:e.room_id,occurred_at:e.occurred_at,evaluated_at:new Date().toISOString(),classification,severity:classification==='ALERT'?'high':classification==='REVIEW'?'medium':'low',rule_id,title,rationale,recommended_action:classification==='OK'?'Continuar monitoramento.':'Solicitar verificação humana.',human_confirmation_required:classification!=='OK',event_snapshot:e,evidence:[`fallback=${note}`],scope:'synthetic-poc'}}
function render(){renderRooms();renderQueue();renderTimeline();renderMetrics()}
function renderRooms(){const rooms=[...state.rooms.values()];$('roomGrid').innerHTML=rooms.length?rooms.map(({event,decision})=>`<article class="room ${decision.classification}"><div class="room-head"><h3>${esc(event.room_id)}</h3><span class="status ${decision.classification}">${label(decision.classification)}</span></div><div class="room-signals"><div class="signal"><span>Presença</span><strong>${event.occupied===null?'Desconhecida':event.occupied?'Ocupado':'Vazio'}</strong></div><div class="signal"><span>Sensor</span><strong>${esc(event.sensor_status)}</strong></div><div class="signal"><span>Climatização</span><strong>${event.hvac_on?'Ligada':'Desligada'}</strong></div><div class="signal"><span>Iluminação</span><strong>${event.light_on?'Ligada':'Desligada'}</strong></div></div><div class="room-foot"><span>${event.power_w??'—'} W observados</span><span>${fmtTime(event.occurred_at)}</span></div></article>`).join(''):'<div class="empty panel">Execute a demo ou envie um evento sintético.</div>'}
function renderQueue(){const pending=state.decisions.filter(d=>d.human_confirmation_required&&!d.resolved);$('queueCount').textContent=pending.length;$('alertQueue').innerHTML=pending.length?pending.map(d=>`<article class="queue-item ${d.classification}"><div class="queue-top"><strong>${esc(d.room_id)} · ${esc(d.title)}</strong><span class="status ${d.classification}">${label(d.classification)}</span></div><p>${esc(d.rationale)}</p><div class="trace"><b>${esc(d.rule_id)}</b> · ${esc(d.recommended_action)}</div><div class="queue-actions"><button class="btn ${d.classification==='REVIEW'?'amber-soft':'primary'}" onclick="resolveDecision('${d.id}','useful')">${d.classification==='REVIEW'?'Revisão concluída':'Confirmar útil'}</button><button class="btn danger-soft" onclick="resolveDecision('${d.id}','false_positive')">Marcar falso</button></div></article>`).join(''):'<div class="empty">Sem pendências.</div>'}
function renderTimeline(){$('timeline').innerHTML=state.decisions.length?state.decisions.map(d=>`<div class="timeline-item"><div class="timeline-time">${fmtTime(d.created_at)}</div><div class="timeline-main"><strong>${esc(d.room_id)} · ${esc(d.title)}</strong><p>${esc(d.rule_id)} · ${d.resolved?'tratado':'recebido'}</p></div><span class="status ${d.classification}">${label(d.classification)}</span></div>`).join(''):'<div class="empty">Nenhum evento nesta sessão.</div>'}
function renderMetrics(){const open=state.decisions.filter(d=>d.human_confirmation_required&&!d.resolved).length,useful=state.confirmations.filter(c=>c.outcome==='useful').length,falsePos=state.confirmations.filter(c=>c.outcome==='false_positive').length,times=state.confirmations.map(c=>c.seconds),avg=times.length?Math.round(times.reduce((a,b)=>a+b,0)/times.length):null;$('mOpen').textContent=open;$('mUseful').textContent=useful;$('mFalse').textContent=falsePos;$('mTime').textContent=avg===null?'—':`${avg}s`}
window.resolveDecision=function(id,outcome){const d=state.decisions.find(x=>x.id===id);if(!d||d.resolved)return;d.resolved=true;d.resolved_at=new Date().toISOString();d.outcome=outcome;state.confirmations.push({decision_id:id,outcome,seconds:Math.max(1,Math.round((new Date(d.resolved_at)-new Date(d.created_at))/1000))});render();toast(outcome==='false_positive'?'Ocorrência marcada como falso alerta.':'Confirmação registrada.')};
$('eventForm').addEventListener('submit',async ev=>{ev.preventDefault();const fd=new FormData(ev.currentTarget);await evaluate({room_id:fd.get('room_id')||'Q-207',occupied:fd.get('occupied')==='null'?null:fd.get('occupied')==='true',sensor_status:fd.get('sensor_status'),hvac_on:fd.get('hvac_on')==='on',light_on:fd.get('light_on')==='on',power_w:Number(fd.get('power_w')||0),synthetic:true});toast('Evento avaliado.')});
$('runDemo').addEventListener('click',async()=>{clearState();for(const scenario of demoScenarios){await evaluate(scenario);await wait(420)}toast('Roteiro carregado: alerta, contexto válido e revisão manual.')});$('resetDemo').addEventListener('click',()=>{clearState();render();toast('Sessão limpa.')});
function clearState(){state.rooms.clear();state.decisions=[];state.confirmations=[]}function wait(ms){return new Promise(r=>setTimeout(r,ms))}function label(v){return v==='ALERT'?'ALERTA':v==='REVIEW'?'REVISÃO':'NORMAL'}function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function toast(msg){const n=document.createElement('div');n.className='toast';n.textContent=msg;document.body.append(n);setTimeout(()=>n.remove(),2400)}
async function checkHealth(){try{const r=await fetch('/api/health',{cache:'no-store'});if(!r.ok)throw 0;$('systemPill').classList.add('online');$('systemPill').innerHTML='<span></span> API online · modo sintético'}catch{$('systemPill').classList.add('offline');$('systemPill').innerHTML='<span></span> API indisponível · fallback local'}}
checkHealth();render();
